package net.nazarick.mapengine.bench;

import net.nazarick.mapengine.core.ColumnBuffer;
import net.nazarick.mapengine.core.ColumnSource;

/**
 * A hand-placed terrain, not a generated one — sea, plains, a small hill, a valley and a mountain,
 * each in its own corner of one 512x512 region, so a rendered picture can be checked against "does
 * this look like a mountain" by eye rather than argued about statistically the way
 * {@link SyntheticWorld}'s deliberately awkward fractal noise has to be. {@link SyntheticWorld} stays
 * the one benchmarks time against — its roughness is the point there — this one exists only to look
 * at a filter's output and know what it is supposed to be looking at.
 */
public final class SceneWorld implements ColumnSource {
    private static final int SEA_LEVEL = SyntheticWorld.SEA_LEVEL;
    private static final int PLAIN = 75;

    @Override
    public boolean fill(int blockX, int blockZ, ColumnBuffer into) {
        for (int z = 0; z < into.width; z++) {
            int worldZ = blockZ + z;
            for (int x = 0; x < into.width; x++) {
                int worldX = blockX + x;
                int index = into.index(x, z);

                int ground = heightAt(worldX, worldZ);
                int surface;
                int depth;
                if (ground < SEA_LEVEL) {
                    surface = SEA_LEVEL;
                    depth = Math.min(ColumnBuffer.MAX_DEPTH, SEA_LEVEL - ground);
                } else {
                    surface = ground;
                    depth = 0;
                }

                into.height[index] = (short) surface;
                // No canopy in this hand-placed scene — the ground is the surface.
                into.groundHeight[index] = (short) surface;
                into.depth[index] = (byte) depth;
                into.block[index] = blockFor(ground, depth);
                into.biome[index] = 0;
            }
        }
        return true;
    }

    private int heightAt(int x, int z) {
        // Sea along the west edge, everything else built up from a flat plain.
        if (x < 110) {
            return 30 + (int) Math.round(6 * Math.sin(z / 25.0)); // a little sea-floor texture, not flat
        }

        // Domain warp: the mountain, hill and valley below are placed with plain circles and a
        // straight trough, and a perfect circle is exactly what reads as "generated by a formula"
        // rather than as ground — real slopes are never that regular. Evaluating them against a
        // noise-displaced coordinate instead of the raw one bends those perfect shapes into the same
        // kind of irregular, organic outline real terrain has, without touching where each feature
        // sits — the mountain is still centred where it was asked to be, just no longer a circle.
        // Kept smaller than the valley's own half-width (30) — a warp bigger than the narrowest
        // feature it is bending fragments that feature into disconnected pieces instead of bending
        // it as one continuous shape, which is what happened at 45 before this was tuned down.
        double warpX = x + fbm(9101, x / 110.0, z / 110.0, 2) * 12.0;
        double warpZ = z + fbm(9102, x / 110.0, z / 110.0, 2) * 12.0;

        double h = PLAIN;
        h += cone(warpX, warpZ, 380, 150, 110, 140);   // the mountain: tall, wide, gentle shoulders
        h += cone(warpX, warpZ, 200, 380, 40, 25);     // the small hill: modest and sharp by comparison
        // The valley: a shallow channel across open plain, well clear of the mountain's own footprint
        // (closest approach is ~170 blocks from the mountain's centre against its 110-block radius),
        // and shallow enough (10 of 75) that its floor never dips below sea level and gets read back
        // as open water — that overlap is exactly the bug the first version of this scene had.
        // Shallower than the first cut (10) so the ±3-block detail noise added below can never push
        // an isolated spot back under sea level — that was the second-order version of the very
        // flooding bug this scene's first draft had, just small enough this time to hide as a few
        // stray sand flecks instead of one obvious blue stripe.
        h -= trough(warpX, warpZ, 300, 300, 480, 470, 40, 6);

        // Fine surface texture, small enough to add grain without disturbing the overall shape —
        // the same role SyntheticWorld's own "detail" octave plays.
        h += fbm(9103, x / 16.0, z / 16.0, 2) * 3.0;

        return (int) Math.round(Math.max(4.0, Math.min(220.0, h)));
    }

    private static double fbm(long seed, double x, double z, int octaves) {
        double sum = 0.0;
        double amplitude = 1.0;
        double total = 0.0;
        for (int i = 0; i < octaves; i++) {
            sum += valueNoise(seed + i * 131L, x, z) * amplitude;
            total += amplitude;
            amplitude *= 0.5;
            x *= 2.0;
            z *= 2.0;
        }
        return sum / total;
    }

    private static double valueNoise(long seed, double x, double z) {
        int x0 = (int) Math.floor(x);
        int z0 = (int) Math.floor(z);
        double fx = x - x0;
        double fz = z - z0;
        double sx = fx * fx * (3.0 - 2.0 * fx);
        double sz = fz * fz * (3.0 - 2.0 * fz);

        double n00 = hash(seed, x0, z0);
        double n10 = hash(seed, x0 + 1, z0);
        double n01 = hash(seed, x0, z0 + 1);
        double n11 = hash(seed, x0 + 1, z0 + 1);

        return lerp(lerp(n00, n10, sx), lerp(n01, n11, sx), sz);
    }

    private static double lerp(double a, double b, double t) {
        return a + (b - a) * t;
    }

    private static double hash(long seed, int x, int z) {
        long h = seed ^ ((long) x * 0x9E3779B97F4A7C15L) ^ ((long) z * 0xC2B2AE3D27D4EB4FL);
        h ^= h >>> 33;
        h *= 0xFF51AFD7ED558CCDL;
        h ^= h >>> 33;
        h *= 0xC4CEB9FE1A85EC53L;
        h ^= h >>> 33;
        return ((h >>> 11) / (double) (1L << 53)) * 2.0 - 1.0; // [-1, 1], centred so the warp bends both ways
    }

    /** A smooth radial bump — {@code peak} blocks tall at the centre, fading to nothing past radius. */
    private static double cone(double x, double z, double cx, double cz, double radius, double peak) {
        double d = Math.hypot(x - cx, z - cz);
        if (d >= radius) {
            return 0.0;
        }
        double t = 1.0 - d / radius;
        return peak * t * t * (3.0 - 2.0 * t); // smoothstep falloff, no hard rim
    }

    /** A smooth depression along the segment from (x0,z0) to (x1,z1), {@code depth} blocks at centre. */
    private static double trough(double x, double z, double x0, double z0, double x1, double z1,
                                  double halfWidth, double depth) {
        double dx = x1 - x0;
        double dz = z1 - z0;
        double lenSq = dx * dx + dz * dz;
        double t = lenSq <= 0 ? 0 : ((x - x0) * dx + (z - z0) * dz) / lenSq;
        t = Math.max(0.0, Math.min(1.0, t));
        double px = x0 + t * dx;
        double pz = z0 + t * dz;
        double d = Math.hypot(x - px, z - pz);
        if (d >= halfWidth) {
            return 0.0;
        }
        double u = 1.0 - d / halfWidth;
        return depth * u * u * (3.0 - 2.0 * u);
    }

    private short blockFor(int ground, int depth) {
        if (depth > 0) {
            return depth > 6 ? SyntheticWorld.BLOCK_GRAVEL : SyntheticWorld.BLOCK_SAND;
        }
        if (ground <= SEA_LEVEL + 2) {
            return SyntheticWorld.BLOCK_SAND;
        }
        if (ground > 180) {
            return SyntheticWorld.BLOCK_SNOW;
        }
        if (ground > 140) {
            return SyntheticWorld.BLOCK_STONE;
        }
        return SyntheticWorld.BLOCK_GRASS;
    }
}
